# Generated by Django 4.2.4 on 2023-08-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(default='  '),
            preserve_default=False,
        ),
    ]
