# Generated by Django 4.2.4 on 2023-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
